# 5.1 Introduction to pandas Data Structures

In [355]:
import pandas as pd

### Series

In [356]:
import numpy as np


In [357]:
from pandas import Series, DataFrame

In [358]:
obj = pd.Series([4, 7, -5, 3])

In [359]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

And so on...

In [360]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [361]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [362]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])

In [363]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [364]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [365]:
obj2["a"]

-5

In [366]:
obj2["d"] = 6

In [367]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [368]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [369]:
import numpy as np

In [370]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [371]:
"b" in obj2

True

In [372]:
"e" in obj2

False

In [373]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}


In [374]:
obj3 = pd.Series(sdata)

In [375]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [376]:
states = ["California", "Ohio", "Oregon", "Texas"]

In [377]:
obj4 = pd.Series(sdata, index= states)

In [378]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [379]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [380]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [381]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [382]:
obj4.notna()


California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [383]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [384]:
type(obj3)

pandas.core.series.Series

In [385]:
obj3.index

Index(['Ohio', 'Texas', 'Oregon', 'Utah'], dtype='object')

In [386]:
obj4


California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [387]:
type(obj4)

pandas.core.series.Series

In [388]:
obj4 + obj3

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [389]:
obj4.name = "population"

In [390]:
obj4.index.name = "state"

In [391]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [392]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [393]:
obj.index = ["Bob","Steve","Jeff","Ryan","chris"]

ValueError: Length mismatch: Expected axis has 4 elements, new values have 5 elements

In [ ]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [ ]:
frame = pd.DataFrame(data)

In [ ]:
frame

In [ ]:
frame.head()

In [ ]:
frame.tail

In [ ]:
pd.DataFrame(data, columns=["years","state","pop"])

In [ ]:
frame2 = pd.DataFrame(data, columns=["years","state","pop","debt"])

In [ ]:
frame2

In [ ]:
frame2.columns

In [ ]:
frame["state"]

In [ ]:
frame2.years

In [ ]:
frame2.state

In [ ]:
frame2.loc[2]

In [ ]:
frame2.iloc[2]

In [ ]:
frame2["debt"] = 16.5

In [ ]:
frame2

In [ ]:
frame2["debt"] = np.arange(6.)

In [ ]:
frame2

In [ ]:
val = pd.Series([-1.2, -1.5, -1.7], index=[2,4,5])

In [ ]:
frame2["debt"] = val

In [ ]:
frame2

In [ ]:
frame2["eastern"] = frame2["state"] == "Ohio"

In [ ]:
frame2

In [ ]:
del frame2["eastern"]

In [ ]:
frame2.columns

In [ ]:
In [72]: populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
   ....:                "Nevada": {2001: 2.4, 2002: 2.9}}

In [ ]:
frame3  = pd.DataFrame(populations)

In [ ]:
frame3

In [ ]:
frame3.T

In [ ]:
frame3

In [ ]:
pd.DataFrame(populations, index=[2001,2002,2003]).T

In [ ]:
In [77]: pdata = {"Ohio": frame3["Ohio"][:-1],
   ....:          "Nevada": frame3["Nevada"][:2]}

In [ ]:
pd.DataFrame(pdata)

In [ ]:
frame3.to_numpy()

In [ ]:
frame2.to_numpy

In [ ]:
obj = pd.Series(np.arange(3), index=["a","b","c"])

In [ ]:
index = obj.index

In [ ]:
index

In [ ]:
index[1:]

In [ ]:
labels = pd.Index(np.arange(3))

In [ ]:
labels

In [ ]:
obj2 = pd.Series([1.5, -2.5,0 ], index=labels)

In [ ]:
obj2

In [ ]:
obj2.index is labels

In [ ]:
frame3

In [ ]:
frame3.index.name = "year"

In [ ]:
frame3.columns.name = "state"

In [ ]:
frame3

In [ ]:
frame3.columns

In [ ]:
"Ohio" in frame3.columns

In [ ]:
2003 in frame3.index

In [ ]:
pd.Index(["foo","foo","bar","bar"])


Table 5.1: Possible data inputs to the DataFrame constructor

vvvvvvvvvv

Type

    -notes


vvvvvvvvvv   


2D ndarray	
    
    -A matrix of data, passing optional row and column labels



Dictionary of arrays, lists, or tuples	
    
    -Each sequence becomes a column in the 
    DataFrame; all sequences must be the same length



NumPy structured/record array	

    -Treated as the “dictionary of arrays” case



Dictionary of Series	

    -Each value becomes a column; indexes from each Series are
    unioned together to form the result’s row index if no explicit index is passed



Dictionary of dictionaries

    -Each inner dictionary becomes a column; keys are unioned to form the row index
    as in the “dictionary of Series” case




List of dictionaries or Series
    
    -Each item becomes a row in the DataFrame; unions of dictionary keys or Series
    indexes become the DataFrame’s column labels



List of lists or tuples	
   
    -Treated as the “2D ndarray” case



Another DataFrame	
   
    -The DataFrame’s indexes are used unless different ones are passed



NumPy MaskedArray	
    
    -Like the “2D ndarray” case except masked values are missing in the DataFrame
    result

In [ ]:
obj = pd.Series([4.5, 7.2, -5.3,3.6], index=["d","b","a","c"])

In [ ]:
obj

In [ ]:
obj2 = obj.reindex(["a","b","c","d","e"])

In [ ]:
obj2

In [ ]:
obj3 = pd.Series(["blue","purple","yellow"], index=[0,2,4])

In [ ]:
obj3

In [ ]:
obj3.reindex(np.arange(6), method="ffill")

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index=["a","c","d"], columns=["Ohio","Texas","California"])

In [ ]:
frame2 = frame.reindex(index=["a","b","c","d"])

In [ ]:
frame2

In [ ]:
states = ["Texas", "Utah", "California"] 

In [ ]:
frame.reindex(columns=states)

In [ ]:
frame.loc[["a","d","c"], ["California","Texas"]]

In [ ]:
obj = pd.Series(np.arange(5.), index=["a","b","c","d","e"])

In [ ]:
obj

In [ ]:
new_obj = obj.drop("c")

In [ ]:
new_obj

In [ ]:
obj.drop(["d","c"])

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index=["Ohio","Colorado","Utah","New York"], columns=["one","two","three","four"]) 

In [ ]:
data

In [ ]:
data.drop(index=["Colorado","Ohio"])

In [ ]:
data

In [ ]:
data.drop(columns=["two"])

In [ ]:
data.drop("two",axis=1)

In [ ]:
data.drop(["two","four"], axis="columns")

In [ ]:
data

In [ ]:
obj = pd.Series(np.arange(4.), index=["a","b","c","d"])

In [ ]:
obj

In [ ]:
obj["b"]

In [ ]:
obj[1]

In [ ]:
obj[2:4]

In [ ]:
obj[["b","a","d"]]

In [ ]:
obj.iloc[[1,3]]

In [ ]:
obj1 = pd.Series([1,2,3], index=[2,0,1])

In [ ]:
obj2 = pd.Series([1,2,3], index=["a","b","c"])

In [ ]:
obj1

In [ ]:
obj2

In [ ]:
obj1[[0,1,2]]

In [ ]:
obj2.iloc[[0,1,2]]

In [ ]:
obj2.loc[[0,1]]

In [ ]:
obj1.iloc[[0,1,2]]

In [ ]:
obj2.iloc[[0,1,2]]

In [ ]:
obj2.loc["b":"c"]

In [ ]:
obj2.loc["b":"c"] = 5

In [ ]:
obj2

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index=["Ohio","Colorado","Utah","New York"], columns=["one","two","three","four"])

In [ ]:
data

In [ ]:
data["two"]

In [ ]:
data[["three","one"]]

In [ ]:
data[:2]

In [ ]:
data[data["three"] > 7 ]

In [ ]:
data < 5 

In [ ]:
data[data < 5] = 0

In [ ]:
data

In [ ]:
data.loc["Colorado"]

In [ ]:
data.loc[["Colorado","New York"]]

In [ ]:
data.loc[["Colorado"], ["two","three"]]

In [ ]:
data.iloc[2]

In [ ]:
data.iloc[2,[3,0,1]]

In [ ]:
data.iloc[[1,2],[3,0,1]]

In [ ]:
data.loc[:"Utah",:"two"]

In [ ]:
data.iloc[:,:3][data.three > 5]

We can index with two slices. that's pretty cool!

In [ ]:
data.loc[data.three >= 2]


Table 5.4: Indexing options with DataFrame

df[column]	Select single column or sequence of columns from the DataFrame; 
special case conveniences: Boolean array (filter rows), slice (slice rows), or Boolean DataFrame (set values based on some criterion)

df.loc[rows]	Select single row or subset of rows from the DataFrame by label

df.loc[:, cols]	Select single column or subset of columns by label

df.loc[rows, cols]	Select both row(s) and column(s) by label

df.iloc[rows]	Select single row or subset of rows from the DataFrame by integer position

df.iloc[:, cols]	Select single column or subset of columns by integer position

df.iloc[rows, cols]	Select both row(s) and column(s) by integer position

df.at[row, col]	Select a single scalar value by row and column label

df.iat[row, col]	Select a single scalar value by row and column position (integers)

reindex method	Select either rows or columns by labels

In [ ]:
ser = pd.Series(np.arange(3.))

In [ ]:
ser

In [ ]:
ser[-1]

In [ ]:
ser

In [ ]:
ser2 = pd.Series(np.arange(3.), index=["a","b","c"])

In [ ]:
ser2.iloc[-1]

In [ ]:
ser[:2]

In [ ]:
data.loc[:,"one"] = 1

In [ ]:
data

In [ ]:
data.iloc[2]= 5

In [ ]:
data

In [ ]:
data.loc[data.four > 5] = 3

In [ ]:
data

In [ ]:
data.loc[data.three == 5]["three"] = 6

In [ ]:
data

In these scenarios, the fix is to rewrite the chained assignment to use a single loc operation:

In [ ]:
data.loc[data.three == 5, "three" ]=6

In [ ]:
data

In [ ]:
s1 = pd.Series([7.3,-2.5,3.4,1.5], index=["a","c","d","e"])

In [ ]:
s2 = pd.Series([-2.1,3.6,-1.5, 4, 3.1], index=["a","c","e","f","g"])

In [ ]:
s1

In [ ]:
s2

In [ ]:
s1 + s2

In [ ]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list("bcd"), index=["Ohio","Texas","Colorado"])

In [ ]:
df1

In [ ]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list("bde"), index=["Utah","Ohio","Texas","Oregon"])

In [ ]:
df2

In [ ]:
df1 + df2

only the rows and comlumns with matching names get added the rest return NAN 

In [ ]:
df1 = pd.DataFrame({"A":[1,2]})

In [ ]:
df2 = pd.DataFrame({"B": [3,4]})

In [ ]:
df1

In [ ]:
df2

In [ ]:
df1 + df2

In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list("abcd"))

In [ ]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list("abcde"))

In [ ]:
df1

In [ ]:
df2

In [ ]:
df2.loc[1,"b"] = np.nan

In [ ]:
df2

In [ ]:
df1 + df2

In [ ]:
df1.add(df2, fill_value=0)

used add() with fill_value=0 to fill in the blanks using the original values from df1. you can alter the values when added by changing "fill_value"

In [394]:
1/ df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [395]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [397]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909


Table 5.5: Flexible arithmetic methods

Method	Description

add, radd	Methods for addition (+)

sub, rsub	Methods for subtraction (-)

div, rdiv	Methods for division (/)

floordiv, rfloordiv	Methods for floor division (//)

mul, rmul	Methods for multiplication (*)

pow, rpow	Methods for exponentiation (**)


In [398]:
arr = np.arange(12.).reshape((3,4))

In [399]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [400]:
arr[0]

array([0., 1., 2., 3.])

In [401]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [402]:
arr - arr[:] 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

had no idea you could do that! cool!

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [410]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list("bde"), index=["Utah","Ohio","Texas","Oregon"])

In [411]:
series = frame.iloc[0]

In [412]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [413]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [414]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [418]:
series2 = pd.Series(np.arange(3), index=list("bef"))

In [419]:
series2

b    0
e    1
f    2
dtype: int64

In [420]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [422]:
series3 = frame["d"]